services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: layoutsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
   build: .
   ports:
     - "8080:8080"
   depends_on:
     - db
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/layoutsdb
     SPRING_DATASOURCE_USERNAME: admin
     SPRING_DATASOURCE_PASSWORD: password
     SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db-data:
